version: "3"
services:
  redis:
    container_name: redis-serve
    image: 'redis:6.0'
    restart: always
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/conf/redis.conf
    command: redis-server /conf/redis.conf
    ports:
      - 6379:6379