version: "3.1"
services:
  seata-server:
    image: seataio/seata-server:1.5.2
    hostname: seata-server
    restart: 'always'
    privileged: true
    ports:
      - "8091:8091"
      - "7091:7091"
    environment:
      # 注册到nacos上的ip。客户端将通过该ip访问seata服务。
      # 注意公网ip和内网ip的差异。
      # 如果使用本地端口映射连接远程seata，则填写本机的内网地址
      # 192.168.253.117
      - SEATA_IP=192.168.56.104
      - TZ=Asia/Shanghai
    volumes:
      - ./conf:/seata-server/resources