image:
  registry: docker.io
  repository: bitnami/redis-cluster
  tag: 7.4.3
  pullPolicy: IfNotPresent

cluster:
  enabled: true
  nodes: 6
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
      port: 6379
      loadBalancerIP:
        - 192.168.56.231  # 对应 redis-cluster-0
        - 192.168.56.232  # 对应 redis-cluster-1
        - 192.168.56.233  # 对应 redis-cluster-2
        - 192.168.56.234  # 对应 redis-cluster-3
        - 192.168.56.235  # 对应 redis-cluster-4
        - 192.168.56.236  # 对应 redis-cluster-5

password: "123456"

persistence:
  enabled: true
  storageClass: ""
  size: 1Gi
  path: /bitnami/redis/data

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring  # 你的 kube-prometheus-stack 安装命名空间
    interval: 15s
    scrapeTimeout: 10s
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi