version: '3'
services:
  elasticsearch:
    container_name: blog-es
    image: 'elasticsearch:7.6.2'
    privileged: true
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms1G -Xmx1Gm" #设置使用jvm内存大小
    volumes:
      - ./es/plugins:/usr/share/elasticsearch/plugins
      - ./es/data:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - blog-nextwork
  kibana:
    image: 'kibana:7.6.2'
    container_name: blog-kibana
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - blog-nextwork
  logstash:
    image: 'logstash:7.6.2'
    container_name: blog-logstash
    environment:
      - TZ=Asia/Shanghai
      - LS_JAVA_OPTS="-Xmx512m -Xms512m"
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./config/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    networks:
      - blog-nextwork


networks:
  blog-nextwork:
    external: true # 指定外部创建的网络，不再创建
