version: '3'
services:
  es:
    container_name: blog-es
    image: 'gagara/elasticsearch-oss-arm64:latest'
    #restart: always
    privileged: false
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
    volumes:
      - ./es/plugins:/usr/share/elasticsearch/plugins
      - ./es/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - blog-nextwork
  kibana:
    image: 'gagara/kibana-oss-arm64:latest'
    container_name: blog-kibana
    #restart: always
    depends_on:
      - es #kibana在elasticsearch启动之后再启动
    environment:
      - "ELASTICSEARCH_HOSTS=http://es:9200"
    ports:
      - 5601:5601
    networks:
      - blog-nextwork
  logstash:
    image: 'gagara/logstash-oss-arm64:latest'
    container_name: blog-logstash
    #restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - es #kibana在elasticsearch启动之后再启动
    ports:
      - 4560:4560
      - 5044:5044
    networks:
      - blog-nextwork
networks:
  blog-nextwork:
    driver: bridge
