version: "3"

services:
  starrocks:
    image: 192.168.56.200:5000/lvlouisaslia/allin1-ubuntu:3.0.0-no-avx2
    container_name: starrocks
    ports:
      - 8030:8030
      - 8040:8040
      - 9030:9030
    healthcheck:
      test: 'mysql -u root -h starrocks-fe -P 9030 -e "show frontends\G" |grep "Alive: true"'
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - version: "3"
