# -*- mode: ruby -*-
# vi: set ft=ruby :

# 定义一个 map 变量，包含虚拟机名称和配置信息
vm_configurations = {
  "chat-gpt" => {
    "box" => "generic/ubuntu2204",
    "network" => "private_network",
    "ip" => "192.168.56.100",
    "memory"=> 32768,
    "cpus"=> 6,
    "shell_path"=> "../scripts/ubuntu2204.sh"
  }
}

Vagrant.configure("2") do |config|
   config.vm.box_check_update = false
   config.ssh.insert_key=false
   config.vm.boot_timeout=30000
   config.disksize.size = '200GB'
   config.vm.synced_folder "D://VirtualBox VMs//share", "/home/vagrant/sync", disabled: false
  # 遍历 map 变量并创建虚拟机
  vm_configurations.each do |vm_name, vm_config|
    config.vm.define vm_name do |vm|
      vm.vm.box = vm_config["box"]
      vm.vm.hostname = vm_name
      vm.vm.network "private_network", ip: vm_config['ip']
      vm.vm.provider "virtualbox" do |vb|
              vb.memory = vm_config['memory']
              vb.cpus = vm_config['cpus']
      end
      vm.vm.provision "shell", path: vm_config["shell_path"]
    end
  end
end