version: "3"
services:
  gogs:
    container_name: gogs-serve
    image: 'gogs/gogs:latest'
    restart: always
    volumes:
      - gogs-data:/data
    environment:
      - TZ=Asia/Shanghai
    privileged: false
    ports:
      - '8022:22'
      - '3000:3000'

volumes:
  gogs-data: