apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-deployment  # 对象的名字
  namespace: cache  # 指定命名空间
spec:
  selector:
    matchLabels:
      app: redis #用来绑定label是“mysql”的Pod
  serviceName: redis # StatefulSet 才有的属性
  replicas: 1
  template:   # 开始定义Pod 
    metadata:
      labels:
        app: redis  #Pod的Label，用来标识Pod
    spec:
      containers: # 开始定义Pod里面的容器
        - image: redis:6.0
          name: redis-service
          imagePullPolicy: IfNotPresent # IfNotPresent  Always  Never
          command:
            - "sh"
            - "-c"
            - "redis-server /conf/redis.conf"
          env:   #  定义环境变量
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 6379 # mysql端口 
              name: redis 
          volumeMounts: # 挂载Pod上的卷到容器
            - name: redis-persistent-storage # Pod上卷的名字，与“volumes”名字匹配
              mountPath: /data # 挂载的Pod的目录
            - name: redis-config
              mountPath: /conf  # 挂载Nginx配置文件路径
      volumes:   # 挂载持久卷到Pod
        - name: redis-persistent-storage # 持久卷名字， 与“volumMounts”名字匹配
          persistentVolumeClaim: 
            claimName: redis-pv-claim  # 持久卷申请名字
        - name: redis-config
          configMap:
            name: redis-configmap  # 引用的ConfigMap的名称