apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: cache  # 指定命名空间
  labels:
    app: redis
spec:
  type: NodePort
  selector:
      app: redis
  ports:
  - protocol : TCP
    nodePort: 30379  #  30000-32767
    port: 6379
    targetPort: 6379