apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
  namespace: cache  # 指定命名空间
  labels:
    app: redis
  annotations:
    kubesphere.io/alias-name: redis-conf
    kubesphere.io/creator: admin
    kubesphere.io/description: redis 主配置文件
data:
  redis.conf: |
      protected-mode no
      port 6379
      requirepass 123456
      bind 0.0.0.0
      appendonly yes
      daemonize no