apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # 你可以根据实际需求修改存储大小
  storageClassName: "local-nfs"  # 根据你的存储类修改

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry
          image: registry:2.8.3
          ports:
            - containerPort: 5000
          env:
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - mountPath: /var/lib/registry
              name: registry-storage
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: registry-pvc
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  selector:
    app: docker-registry
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050  # 你可以修改这个端口
  type: NodePort
