version: "3.1"
services:
  sentinel-server:
    container_name: sentinel-serve
    image: xiaojun207/sentinel-dashboard:1.8.6
    hostname: sentinel-server
    restart: 'always'
    privileged: true
    ports:
      - "8858:8021"
    environment:
      - TZ=Asia/Shanghai