version: "3"
services:
  zookeeper01:
    image: bitnami/zookeeper:3.9.3
    restart: always
    container_name: zookeeper01
    ports:
      - 2182:2181
    volumes:
      - zookeeper01-data:/data
      - ./zookeeper01/datalog:/datalog
    environment:
      - TZ=Asia/Shanghai
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper01:2888:3888,zookeeper02:2888:3888,zookeeper03:2888:3888
    networks:
      - zookeeper-net
  zookeeper02:
    image: bitnami/zookeeper:3.9.3
    restart: always
    container_name: zookeeper02
    ports:
      - 2183:2181
    volumes:
      - zookeeper02-data:/data
      - ./zookeeper02/datalog:/datalog
    environment:
      - TZ=Asia/Shanghai
      - ZOO_SERVER_ID=2
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper01:2888:3888,zookeeper02:2888:3888,zookeeper03:2888:3888
    networks:
      - zookeeper-net
  zookeeper03:
    image: bitnami/zookeeper:3.9.3
    restart: always
    container_name: zookeeper03
    ports:
      - 2184:2181
    volumes:
      - zookeeper03-data:/data
      - ./zookeeper03/datalog:/datalog
    environment:
      - TZ=Asia/Shanghai
      - ZOO_SERVER_ID=3
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper01:2888:3888,zookeeper02:2888:3888,zookeeper03:2888:3888
    networks:
      - zookeeper-net
  kafka-0:
    image: bitnami/kafka:3.3
    container_name: kafka-0
    restart: always
    ports:
      - "32768:9092"
    environment:
      - TZ=Asia/Shanghai
      # KRaft settings
#      - KAFKA_CFG_NODE_ID=0
#      - KAFKA_CFG_PROCESS_ROLES=controller,broker
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
#      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      # Listeners
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.56.50:32768
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Clustering
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
      #zookeeper
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper01:2181,zookeeper01:2181,zookeeper01:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    volumes:
      - kafka_0_data:/bitnami/kafka
    networks:
      - zookeeper-net
    depends_on:
      - zookeeper01
      - zookeeper02
      - zookeeper03
  kafka-1:
    image: bitnami/kafka:3.3
    container_name: kafka-1
    restart: always
    ports:
      - "32769:9092"
    environment:
      - TZ=Asia/Shanghai
      # KRaft settings
#      - KAFKA_CFG_NODE_ID=1
#      - KAFKA_CFG_PROCESS_ROLES=controller,broker
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
#      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      # Listeners
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.56.50:32769
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Clustering
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
      #zookeeper
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper01:2181,zookeeper01:2181,zookeeper01:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    volumes:
      - kafka_1_data:/bitnami/kafka
    networks:
      - zookeeper-net
    depends_on:
      - zookeeper01
      - zookeeper02
      - zookeeper03
  kafka-2:
    image:  bitnami/kafka:3.3
    container_name: kafka-2
    restart: always
    ports:
      - "32770:9092"
    environment:
      - TZ=Asia/Shanghai
      # KRaft settings
#      - KAFKA_CFG_NODE_ID=2
#      - KAFKA_CFG_PROCESS_ROLES=controller,broker
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
#      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      # Listeners
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.56.50:32770
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Clustering
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
      #zookeeper
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper01:2181,zookeeper01:2181,zookeeper01:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    volumes:
      - kafka_2_data:/bitnami/kafka
    networks:
      - zookeeper-net
    depends_on:
      - zookeeper01
      - zookeeper02
      - zookeeper03
volumes:
  kafka_0_data:
    driver: local
  kafka_1_data:
    driver: local
  kafka_2_data:
    driver: local
  zookeeper01-data:
    driver: local
  zookeeper02-data:
    driver: local
  zookeeper03-data:
    driver: local
networks:
  zookeeper-net:
    driver: bridge