
- name: Run installation script
  shell: $HOME/ansible/roles/common/files/install_docker.sh

- name: check if install docker-compose
  stat:
    path: /usr/local/bin/docker-compose
  register: composeInstalled

- name: install docker-compose
  command: sh -c 'curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose'
  when: composeInstalled.stat.exists == False

- name: chmod docker-compose
  file:
    path: /usr/local/bin/docker-compose
    mode: 0744

# 重启docker 
- service: name=docker state=restarted