---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: springcloud
  labels:
    app: nacos-headless
spec:
  type: NodePort
  ports:
    - protocol : TCP
      nodePort: 30848  #  30000-32767
      port: 8848
      targetPort: 8848
      name: web
    - protocol : TCP
      nodePort: 30948  #  30000-32767
      port: 9848
      targetPort: 9848
      name: rpc
    - protocol : TCP
      nodePort: 30949  #  30000-32767
      port: 9849
      targetPort: 9849
      name: raft-rpc
    - protocol : TCP
      nodePort: 30748  #  30000-32767
      port: 7848
      targetPort: 7848
      name: old-raft-rpc
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
  namespace: springcloud
  labels:
    app: nacos-headless
data:
  mysql.host: "mysql-service.database"
  mysql.db.name: "nacos_devtest"
  mysql.port: "3306"
  mysql.user: "nacos"
  mysql.password: "nacos_dev"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: springcloud
spec:
  selector:
    matchLabels:
      app: nacos
  serviceName: nacos-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos
              topologyKey: "app.kubernetes.io/name"
      containers:
        - name: nacos
          imagePullPolicy: IfNotPresent
          image: nacos/nacos-server:2.0.3
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 9848
              name: client-rpc
            - containerPort: 9849
              name: raft-rpc
            - containerPort: 7848
              name: old-raft-rpc
          env:
            - name: NACOS_REPLICAS
              value: "3"
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.host
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: SPRING_DATASOURCE_PLATFORM
              value: "mysql"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: NACOS_APPLICATION_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.springcloud.svc.cluster.local:8848 nacos-1.nacos-headless.springcloud.svc.cluster.local:8848 nacos-2.nacos-headless.springcloud.svc.cluster.local:8848"
