version: "3"
services:
  nacos:
    image: nacos/nacos-server:2.0.3
    container_name: nacos-standalone-mysql
    env_file:
      #需要先安装好mysql， 注意初始化sql
      - ./nacos-standlone-mysql.env  
    volumes:
      - ./standalone-logs/:/home/nacos/logs  #日志
      - ./custom.properties:/home/nacos/init.d/custom.properties #初始化配置
    ports:
      - "8848:8848"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8848/nacos/v1/console/health/liveness || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3