# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box_check_update = false
    config.ssh.insert_key = false
    
    # 设置全局超时时间和 SSH 配置
    config.vm.boot_timeout = 1200
    config.vm.graceful_halt_timeout = 120

    config.vm.provision "shell", inline: <<-SHELL
      grep -q "192.168.56.80 master" /etc/hosts || echo "192.168.56.80 master" >> /etc/hosts
      grep -q "192.168.56.81 worker1" /etc/hosts || echo "192.168.56.81 worker1" >> /etc/hosts
      grep -q "192.168.56.82 worker2" /etc/hosts || echo "192.168.56.82 worker2" >> /etc/hosts
      swapoff -a
    SHELL

    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    config.vm.define "master" do |master|
            master.vm.box = "ubuntu/jammy64"
            master.vm.hostname = "master"
            master.vm.network "private_network", ip: "192.168.56.80", auto_config: true
            master.vm.provider "virtualbox" do |vb|
                    vb.memory = 16384
                    vb.cpus = 2
            end
            master.vm.provision "shell", path: "scripts/common.sh", privileged: true
            master.vm.provision "shell", path: "scripts/k3s-master.sh", privileged: true
    end
    
    (1..2).each do |i|
            config.vm.define "worker#{i}" do |worker|
                    worker.vm.box = "ubuntu/jammy64"
                    worker.vm.hostname = "worker#{i}"
                    worker.vm.network "private_network", ip: "192.168.56.8#{i}", auto_config: true
                    worker.vm.provider "virtualbox" do |vb|
                              vb.memory = 16384
                              vb.cpus = 2
                    end
                    worker.vm.provision "shell", path: "scripts/common.sh", privileged: true
                    worker.vm.provision "shell", path: "scripts/k3s-worker.sh", privileged: true
            end
    end
end