global:
  storageClass: ""  # 根据你的集群设置

image:
  registry: docker.io
  repository: bitnami/elasticsearch
  tag: 8.12.2  # 或你想指定的版本
  pullPolicy: IfNotPresent


replicas: 1
minimumMasterNodes: 1

master:
  replicaCount: 1
  persistence:
    enabled: true
    size: 5Gi

data:
  replicaCount: 1
  persistence:
    enabled: true
    size: 10Gi

coordinating:
  replicaCount: 1
  persistence:
    enabled: true
    size: 5Gi
  service:
    type: LoadBalancer
