image:
  repository: bitnami/fluent-bit
  tag: 2.2.0

daemonset:
  enabled: true

config:
  inputs: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5

  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

  outputs: |
    [OUTPUT]
        Name            kafka
        Match           *
        Brokers         kafka-kraft.kafka.svc.cluster.local:9092
        Topics          fluent-bit-log
        Retry_Limit     False
        rdkafka.queue.buffering.max.kbytes 10240
        rdkafka.request.required.acks      1

