image:
  repository: bitnami/fluent-bit
  tag: 2.2.0

daemonset:
  enabled: false
replicaCount: 1


resources:
  limits:
    memory: 200Mi
    cpu: 200m
  requests:
    memory: 100Mi
    cpu: 100m




config:
  inputs: |
    [INPUT]
        Name              kafka
        Brokers           kafka-kraft.kafka.svc.cluster.local:9092
        Topics            fluent-bit-log
        Group_Id          fluent-bit
        Tag               kafka.*

  outputs: |
    [OUTPUT]
        Name            es
        Match           *
        Host            elasticsearch.search-platform.svc.cluster.local
        Port            9200
        Logstash_Format   On
        Replace_Dots      On
        Suppress_Type_Name On
        Retry_Limit       False
        Logstash_Prefix   fluentbit
        Logstash_DateFormat %Y.%m.%d