input:
  tail:
    enabled: true
    path: /var/log/containers/*.log
    parser: docker
    tag: kube.*
    dockerMode: true
    multiline:
      enabled: true
    refreshInterval: 5
    memBufLimit: 10MB
    skipLongLines: true

parser:
  enabled: true
  parsers:
    docker:
      Name: docker
      Format: json
      Time_Key: time
      Time_Format: "%Y-%m-%dT%H:%M:%S.%L"
      Time_Keep: On

filter:
  kubernetes:
    enabled: true
    match: kube.*
    mergeLog: On
    mergeLogKey: log
    keepLog: Off
    labels: On
    annotations: Off

  modify:
    enabled: true
    match: kube.*
    remove:
      - stream
      - docker_id
      - kubernetes.annotations
      - kubernetes.labels."pod-template-hash"
    rename:
      log: message

output:
  kafka:
    enabled: true
    brokers: kafka-kraft.kafka.svc.cluster.local:9092
    topics: logs-topic
    timestamp_key: @timestamp
    rdkafka:
      log.connection.error: true
      request.required.acks: 1
