apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: test  # 指定命名空间
  labels:
    app: nginx
  annotations:
    kubesphere.io/alias-name: nginx-conf
    kubesphere.io/creator: admin
    kubesphere.io/description: nginx 主配置文件
data:
  default.conf: |-
    server {
        listen 80;
        server_name localhost;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /cnblogs/ {
            rewrite ^(.*)$ http://www.cnblogs.com/;
        }
    }
