version: "3"
services:
  nginx:
    container_name: blog-nginx
    image: 'nginx:1.16-alpine'
    restart: always
    privileged: true
    volumes:
      #- ./volumes/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      #- ./volumes/nginx/certs/full_chain.pem:/etc/nginx/certs/full_chain.pem
      #- ./volumes/nginx/certs/private.key:/etc/nginx/certs/private.key
      #- ./volumes/nginx/logs:/var/log/nginx
      - ./volumes/nginx/www:/home/www/website
    ports:
      - 80:80
      - 443:443