version: "3"
services:
  mysql:
    container_name: gogs-serve
    image: 'gogs/gogs-rpi'
    restart: always
    #privileged: true
    volumes:
      - ./data:/data
    ports:
      - '10022:22'
      - '10080:3000'