version: "3"
services:
  mysql:
    container_name: mysql-serve
    image: 'mysql:8.0'
    restart: always
    privileged: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
  oracle:
    container_name: oracle_serve
    image: 'acktsw/oracle-xe-11g'
    restart: always
    privileged: true
    ports:
      - 1521:1521
    volumes:
      - ./volumes/oracle:/u01/app/oracle
  redis:
    container_name: redis-serve
    image: 'redis:6.0'
    restart: always
    privileged: true
    volumes:
      - ./volumes/redis/data:/data
    ports:
      - 6379:6379
  mq:
    container_name: rabbitmq-serve
    image: 'rabbitmq:3.8-management'
    restart: always
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
  nginx:
    container_name: blog-nginx
    image: 'nginx:1.16-alpine'
    restart: always
    privileged: true
    volumes:
      #- ./volumes/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      #- ./volumes/nginx/certs/full_chain.pem:/etc/nginx/certs/full_chain.pem
      #- ./volumes/nginx/certs/private.key:/etc/nginx/certs/private.key
      #- ./volumes/nginx/logs:/var/log/nginx
      - ./volumes/nginx/www:/home/www/website
    ports:
      - 80:80
      - 443:443