version: "3"
services:
  mysql:
    container_name: mysql-serve
    image: 'mysql:8.0'
    restart: always
    privileged: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /opt/mysql/data:/var/lib/mysql
      - /opt/mysql/conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    networks:
      - blog-extranet
  oracle:
    container_name: oracle_serve
    image: 'acktsw/oracle-xe-11g'
    restart: always
    privileged: true
    ports:
      - 1521:1521
    volumes:
      - /opt/oracle:/u01/app/oracle
    networks:
      - blog-extranet
  redis:
    container_name: redis-serve
    image: 'redis:6.0'
    restart: always
    privileged: true
    volumes:
      - /opt/redis/data:/data
      - /opt/redis/conf/redis.conf:/conf/redis.conf
    command: redis-server /conf/redis.conf
    networks:
      - blog-extranet
    ports:
      - 6379:6379
  mq:
    container_name: rabbitmq-serve
    image: 'rabbitmq:3.8-management'
    restart: always
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - blog-extranet

networks:
  blog-extranet:
    external: true # 指定外部创建的网络，不再创建
