version: "3"
services:
  xxl-job:
    image: xuxueli/xxl-job-admin:2.3.0
    container_name: xxl-job-server
    environment:
      # 注意用空格分割每一个参数
      - PARAMS=" --server.port=9090 --spring.datasource.url=jdbc:mysql://192.168.56.10:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=123456 "
    volumes:
      - xxl-job:/data
    ports:
      - "7070:9090"
    restart: always

volumes:
  xxl-job: