# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box_check_update = false
    config.ssh.insert_key=false

    config.vm.provision "shell", inline: <<-SHELL
            echo "192.168.56.80  master" >> /etc/hosts
            echo "192.168.56.81  worker1" >> /etc/hosts
            echo "192.168.56.82  worker2" >> /etc/hosts
            echo "192.168.56.83  worker2" >> /etc/hosts
    SHELL

    config.vm.define "master" do |master|
            master.vm.box = "ubuntu/bionic64"
            master.vm.hostname = "master"
            master.vm.network "private_network", ip: "192.168.56.80"
            master.vm.provider "virtualbox" do |vb|
                    vb.memory = 8196
                    vb.cpus = 4
            end
            master.vm.provision "shell", path: "scripts/common.sh"
            #   master.vm.provision "shell", path: "scripts/master.sh"
    end
    
    (1..3).each do |i|
            config.vm.define "worker#{i}" do |worker|
                    worker.vm.box = "ubuntu/bionic64"
                    worker.vm.hostname = "worker#{i}"
                    worker.vm.network "private_network", ip: "192.168.56.8#{i}"
                    worker.vm.provider "virtualbox" do |vb|
                              vb.memory = 16384  
                              vb.cpus = 4
                    end
                    worker.vm.provision "shell", path: "scripts/common.sh"
                    # worker.vm.provision "shell", path: "scripts/worker.sh"
            end
    end
end