version: "3"
services:
  nginx:
    container_name: blog-nginx
    image: 'nginx:1.16-alpine'
    restart: always
    privileged: true
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443