version: '3.0'

services:
  apollo-quick-start:
    image: nobodyiam/apollo-quick-start
    container_name: apollo-quick-start
    restart: 'always'
    depends_on:
      apollo-db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8070:8070"
      - "8090:8090"
    links:
      - apollo-db
    environment:
      TZ: Asia/Shanghai
      #JAVA_OPTS: '-Xms2048m -Xmx2048m -Xmn1000m -Xss512k -XX:MetaspaceSize=10m -XX:MaxMetaspaceSize=512m'
#      APOLLO_CONFIG_DB_USERNAME: 'root'
#      APOLLO_CONFIG_DB_PASSWORD: 'apollo'
#      APOLLO_PORTAL_DB_USERNAME: 'root'
#      APOLLO_PORTAL_DB_PASSWORD: 'apollo'

  apollo-db:
    image: mysql:8.0
    container_name: apollo-db
    restart: 'always'
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      #MYSQL_ROOT_PASSWORD: 'apollo'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 1s
      retries: 10
    depends_on:
      - apollo-dbdata
    ports:
      - "13306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    volumes_from:
      - apollo-dbdata

  apollo-dbdata:
    image: alpine:latest
    container_name: apollo-dbdata
    volumes:
      - ./mysql_data:/var/lib/mysql