version: "3"
services:
  nexus3:
    image: 'sonatype/nexus3:3.40.0'
    container_name: nexus3-service
    # no，on-failure[:times]，always，unless-stopped
    restart: 'always'
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - INSTALL4J_ADD_VM_PARAMS=-Xms2048m -Xmx2048m -XX:MaxDirectMemorySize=1024m
    ports:
      - '5555:8081'
      - '6666:6666'
      - '6667:6667'
    volumes:
      - nexus3-data:/nexus-data

volumes:
  nexus3-data: