# -*- mode: ruby -*-
# vi: set ft=ruby :

# 定义一个 map 变量，包含虚拟机名称和配置信息
vm_configurations = {
  "mysql" => {
    "box" => "ubuntu/bionic64",
    "network" => "private_network",
    "ip" => "192.168.56.10",
    "memory"=> 4096,
    "cpus"=> 2
  },
  "redis" => {
    "box" => "ubuntu/bionic64",
    "network" => "private_network",
    "ip" => "192.168.56.11",
    "memory"=> 4096,
    "cpus"=> 2
  },
  "elk" => {
    "box" => "ubuntu/bionic64",
    "network" => "private_network",
    "ip" => "192.168.56.12",
    "memory"=> 16384,
    "cpus"=> 8
  },
  "mq" => {
    "box" => "ubuntu/bionic64",
    "network" => "private_network",
    "ip" => "192.168.56.13",
    "memory"=> 8192,
    "cpus"=> 4
  },
  "harbor" => {
    "box" => "ubuntu/bionic64",
    "network" => "private_network",
    "ip" => "192.168.56.14",
    "memory"=> 8192,
    "cpus"=> 4
  },
  "git" => {
    "box" => "ubuntu/bionic64",
    "network" => "private_network",
    "ip" => "192.168.56.15",
    "memory"=> 2048,
    "cpus"=> 2
  },
  "monitor" => {
    "box" => "ubuntu/bionic64",
    "network" => "private_network",
    "ip" => "192.168.56.16",
    "memory"=> 4096,
    "cpus"=> 4
  },
  "web" => {
    "box" => "ubuntu/bionic64",
    "network" => "private_network",
    "ip" => "192.168.56.17",
    "memory"=> 4096,
    "cpus"=> 4
  }
}

Vagrant.configure("2") do |config|
   config.vm.box_check_update = false
   config.ssh.insert_key=false
  # 遍历 map 变量并创建虚拟机
  vm_configurations.each do |vm_name, vm_config|
    config.vm.define vm_name do |vm|
      vm.vm.box = vm_config["box"]
      vm.vm.box = "ubuntu/bionic64"
      vm.vm.hostname = vm_name
      vm.vm.network "private_network", ip: vm_config['ip']
      vm.vm.provider "virtualbox" do |vb|
              vb.memory = vm_config['memory']
              vb.cpus = vm_config['cpus']
      end
      vm.vm.provision "shell", path: "kubesphere/scripts/common.sh"
    end
  end
end