apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: database  # 指定命名空间
  labels:
    app: mysql
  annotations:
    kubesphere.io/alias-name: mysql-conf
    kubesphere.io/creator: admin
    kubesphere.io/description: mysql 主配置文件
data:
  my.conf: |
      [mysqld]
      secure-file-priv = NULL
      #忽略表大小写
      lower_case_table_names = 1
      #密码验证插件
      default-authentication-plugin=mysql_native_password
      [client]
      default-character-set=utf8mb4
      [mysql]
      default-character-set=utf8mb4