apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: database  # 指定命名空间
  labels:
    app: mysql
spec:
  type: NodePort
  selector:
      app: mysql
  ports:
  - protocol : TCP
    nodePort: 30306  #  30000-32767
    port: 3306
    targetPort: 3306 