# apollo-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: apollo
---
# apollo-configservice-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo-configservice
  namespace: apollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo-configservice
  template:
    metadata:
      labels:
        app: apollo-configservice
    spec:
      containers:
        - name: apollo-configservice
          image: apolloconfig/apollo-configservice:2.2.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://192.168.56.80:30033/ApolloConfigDB?characterEncoding=utf8&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
            - name: EUREKA_INSTANCE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVER_PORT
              value: "8080"
#            - name: eureka.client.enabled
#              value: "false"
#            - name: eureka.server.enabled
#              value: "false"
---
# apollo-adminservice-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo-adminservice
  namespace: apollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo-adminservice
  template:
    metadata:
      labels:
        app: apollo-adminservice
    spec:
      containers:
        - name: apollo-adminservice
          image: apolloconfig/apollo-adminservice:2.2.0
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://192.168.56.80:30033/ApolloConfigDB?characterEncoding=utf8&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
            - name: SERVER_PORT
              value: "8090"
#            - name: eureka.client.enabled
#              value: "false"
#            - name: eureka.server.enabled
#              value: "false"
---
# apollo-portal-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo-portal
  namespace: apollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo-portal
  template:
    metadata:
      labels:
        app: apollo-portal
    spec:
      containers:
        - name: apollo-portal
          image: apolloconfig/apollo-portal:2.2.0
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://192.168.56.80:30033/ApolloPortalDB?characterEncoding=utf8&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
            - name: SERVER_PORT
              value: "8070"
            - name: APOLLO_PORTAL_ENVS
              value: dev
            - name: DEV_META
              value: http://apollo-configservice.apollo.svc.cluster.local:8080

---
# apollo-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: apollo-configservice
  namespace: apollo
spec:
  type: NodePort
  selector:
    app: apollo-configservice
  ports:
    - port: 8080
      targetPort: 8080
      #nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: apollo-adminservice
  namespace: apollo
spec:
  type: NodePort
  selector:
    app: apollo-adminservice
  ports:
    - port: 8090
      targetPort: 8090
      #nodePort: 30090
---
apiVersion: v1
kind: Service
metadata:
  name: apollo-portal
  namespace: apollo
spec:
  type: NodePort
  selector:
    app: apollo-portal
  ports:
    - port: 8070
      targetPort: 8070
      #nodePort: 30070
