apiVersion: v1
kind: Service
metadata:
  name: gogs-service
  namespace: git  # 指定命名空间
  labels:
    app: gogs
spec:
  type: NodePort
  selector:
      app: gogs
  ports:
  - protocol : TCP
    name: ssh
    nodePort: 30022  #  30000-32767
    port: 22
    targetPort: 22
  - protocol : TCP
    name: http
    nodePort: 30300  #  30000-32767
    port: 3000
    targetPort: 3000