apiVersion: v1
kind: Namespace
metadata:
  name: git

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-pvc
  namespace: git
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "local-nfs"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogs
  namespace: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  template:
    metadata:
      labels:
        app: gogs
    spec:
      containers:
        - name: gogs
          image: 'gogs/gogs:0.13'
          ports:
            - containerPort: 3000
            - containerPort: 22
          env:   #  定义环境变量
            - name: TZ
              value: Asia/Shanghai
            - name: SOCAT_LINKS
              value: "false"
            - name: GOGS_CUSTOM
              value: /data/gogs
          volumeMounts:
            - mountPath: /data
              name: gogs-data
      volumes:
        - name: gogs-data
          persistentVolumeClaim:
            claimName: gogs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: gogs
  namespace: git
spec:
  selector:
    app: gogs
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080  # 你可以修改这个端口
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022  # 你可以修改这个端口
  type: NodePort

