version: "3.7"
services:
  minio:
   image: "quay.io/minio/minio:RELEASE.2022-08-02T23-59-16Z"
   ports:
    - "9000:9000"
    - "9001:9001"
   volumes:
    - "minio-data1:/data1"
    - "minio-data2:/data2"
   command: server --console-address ":9001" http://minio/data{1...2}
   environment:
    - MINIO_ROOT_USER=admin
    - MINIO_ROOT_PASSWORD=123456
   #- MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
   #- MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
   healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
volumes:
  minio-data1:
  minio-data2: