version: '3'


services:
  prometheus:
    image: bitnami/prometheus:2.47.2
    container_name: prometheus
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./web-config.yml:/etc/prometheus/web-config.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web-config.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    ports:
      - 9901:9090
    networks:
      - monitor-net


  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456   # 设置 Grafana 的管理员密码
      - TZ=Asia/Shanghai
    ports:
      - 9902:3000
    networks:
      - monitor-net

  nodeexporter:
    image: prom/node-exporter:v1.5.0
    container_name: nodeexporter
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "/:/host:ro,rslave"
    command:
      - '--path.rootfs=/host'
    ports:
      - 9100:9100
    networks:
      - monitor-net

  mysqld-exporter-master:
    image: prom/mysqld-exporter:v0.15.0
    container_name: mysqld-exporter-master
    ports:
      - 9101:9104
    environment:
      - MYSQLD_EXPORTER_PASSWORD=123456
      - TZ=Asia/Shanghai
    networks:
      - monitor-net
    command:
      - '--web.listen-address=:9104'
      - '--mysqld.address=192.168.56.200:4400'
      - '--mysqld.username=exporter'
  mysqld-exporter-slave1:
    image: prom/mysqld-exporter:v0.15.0
    container_name: mysqld-exporter-slave1
    ports:
      - 9102:9104
    environment:
      - MYSQLD_EXPORTER_PASSWORD=123456
      - TZ=Asia/Shanghai
    networks:
      - monitor-net
    command:
      - '--web.listen-address=:9104'
      - '--mysqld.address=192.168.56.200:4401'
      - '--mysqld.username=exporter'
  mysqld-exporter-slave2:
    image: prom/mysqld-exporter:v0.15.0
    container_name: mysqld-exporter-slave2
    ports:
      - 9103:9104
    environment:
      - MYSQLD_EXPORTER_PASSWORD=123456
      - TZ=Asia/Shanghai
    networks:
      - monitor-net
    command:
      - '--web.listen-address=:9104'
      - '--mysqld.address=192.168.56.200:4402'
      - '--mysqld.username=exporter'

  redis-exporter-6031:
      image: 'oliver006/redis_exporter:v1.61.0'
      container_name: redis-exporter-6031
      environment:
        - REDIS_ADDR=redis://192.168.56.200:6301
        - TZ=Asia/Shanghai
      ports:
        - 9121:9121
      networks:
        - monitor-net
  redis-exporter-6032:
      image: 'oliver006/redis_exporter:v1.61.0'
      container_name: redis-exporter-6032
      environment:
        - REDIS_ADDR=redis://192.168.56.200:6302
        - TZ=Asia/Shanghai
      ports:
        - 9122:9121
      networks:
        - monitor-net      
  redis-exporter-6033:
      image: 'oliver006/redis_exporter:v1.61.0'
      container_name: redis-exporter-6033
      environment:
        - REDIS_ADDR=redis://192.168.56.200:6303
        - TZ=Asia/Shanghai
      ports:
        - 9123:9121
      networks:
        - monitor-net      
  redis-exporter-6034:
      image: 'oliver006/redis_exporter:v1.61.0'
      container_name: redis-exporter-6034
      environment:
        - REDIS_ADDR=redis://192.168.56.200:6304
        - TZ=Asia/Shanghai
      ports:
        - 9124:9121
      networks:
        - monitor-net      
  redis-exporter-6035:
      image: 'oliver006/redis_exporter:v1.61.0'
      container_name: redis-exporter-6035
      environment:
        - REDIS_ADDR=redis://192.168.56.200:6305
        - TZ=Asia/Shanghai
      ports:
        - 9125:9121
      networks:
        - monitor-net      
  redis-exporter-6036:
      image: 'oliver006/redis_exporter:v1.61.0'
      container_name: redis-exporter-6036
      environment:
        - REDIS_ADDR=redis://192.168.56.200:6306
        - TZ=Asia/Shanghai
      ports:
        - 9126:9121
      networks:
        - monitor-net      
  kafka-exporter:
    image: bitnami/kafka-exporter:latest
    container_name: kafka-exporter
    command:
      - '--kafka.server=192.168.56.50:32767'
      - '--kafka.server=192.168.56.50:32768'
      - '--kafka.server=192.168.56.50:32769'
      - '--kafka.version=3.8.0'
    restart: always
    ports:
      - 9308:9308


networks:
  monitor-net:
    driver: bridge
volumes:
  prometheus-data:
  grafana-data: