global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.56.200:9901']
    # 启用了账号密码 web-config.yml basic_auth_users 需要配置
    # Bcrypt密码生成工具
    basic_auth:
      username: root
      password: 123456
  - job_name: 'prometheus-linux'
    # 每隔5秒从该作业中抓取目标
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.56.60:9100']
  - job_name: 'mysql'
    # 每隔5秒从该作业中抓取目标
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.56.60:9101','192.168.56.60:9102','192.168.56.60:9103']
  ## config for scraping the exporter itself
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - 192.168.56.60:9121
        - 192.168.56.60:9122
        - 192.168.56.60:9123
        - 192.168.56.60:9124
        - 192.168.56.60:9125
        - 192.168.56.60:9126
  - job_name: jenkins
    metrics_path: '/prometheus'
    static_configs:
    - targets:
      - 192.168.56.60:8500
  - job_name: nacos
    metrics_path: '/nacos/actuator/prometheus'
    static_configs:
      - targets: ['192.168.56.60:8848']
  - job_name: 'kafka-exporter'
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - 192.168.56.60:9308
        labels:
          name: publicmq